# Generated by Django 5.1.4 on 2024-12-29 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="last_name",
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
