# Generated by Django 5.1.1 on 2024-12-29 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_remove_patient_user_patient_first_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(blank=True, default="", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_number",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(default="Not Provided"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                default="patient@example.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(default="John", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(default="Doe", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Medical Consultation"),
                            ("PRESCRIPTION", "Prescription"),
                            ("TEST_RESULT", "Test Result"),
                            ("ADMISSION", "Hospital Admission"),
                            ("DISCHARGE", "Hospital Discharge"),
                        ],
                        default="CONSULTATION",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(default="")),
                ("doctor_name", models.CharField(default="Unknown", max_length=100)),
                ("date_of_record", models.DateTimeField(auto_now_add=True)),
                (
                    "additional_notes",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
