# Generated by Django 5.1.4 on 2024-12-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0004_patient_blood_group_patient_emergency_contact_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
    ]
