# Generated by Django 5.1.4 on 2024-12-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_tag_orders_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="tag",
        ),
        migrations.AddField(
            model_name="products",
            name="tag",
            field=models.ManyToManyField(to="accounts.tag"),
        ),
    ]
