# Generated by Django 5.1.4 on 2024-12-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_orders_tag_products_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
