# Generated by Django 5.1.4 on 2024-12-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_products_description_products_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="product",
        ),
        migrations.RemoveField(
            model_name="products",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Customers",
        ),
        migrations.DeleteModel(
            name="Orders",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
